/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CbAlert {
    }
}
declare global {
    interface HTMLCbAlertElement extends Components.CbAlert, HTMLStencilElement {
    }
    var HTMLCbAlertElement: {
        prototype: HTMLCbAlertElement;
        new (): HTMLCbAlertElement;
    };
    interface HTMLElementTagNameMap {
        "cb-alert": HTMLCbAlertElement;
    }
}
declare namespace LocalJSX {
    interface CbAlert {
    }
    interface IntrinsicElements {
        "cb-alert": CbAlert;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cb-alert": LocalJSX.CbAlert & JSXBase.HTMLAttributes<HTMLCbAlertElement>;
        }
    }
}
